sonar.projectKey=gamedash-frontend
sonar.projectName=GameDash Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/__tests__/**

sonar.sourceEncoding=UTF-8
